### ISSUE TITLE
source not found when building docker image

### ISSUE THREAD

**Issue by LanderU** [ros-realtime/rt-kernel-docker-builder#1]
Hey!

I'm checking out this work, and looks like something is not well configured or we're missing some sources. When I try to build the docker image with the instructions it ends into an error fetching the build deps for the linux image. See the error attached:

```bash
E: Unable to find a source package for linux-image-5.4.0-1022-raspi
The command '/bin/sh -c apt-get update && apt-get build-dep -q -y linux linux-image-${UNAME_R}     && apt-get install -q -y     libncurses-dev flex bison openssl libssl-dev dkms libelf-dev libudev-dev libpci-dev libiberty-dev autoconf     fakeroot     && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100
```

Is failling on this line: https://github.com/ros-realtime/rt-kernel-docker-builder/blob/master/.gitpod.Dockerfile#L49

And also will file at: https://github.com/ros-realtime/rt-kernel-docker-builder/blob/master/.gitpod.Dockerfile#L62

**Comment by razr** [comment]
@LanderU thanks for testing it. There is a new raspi image that Ubuntu provides linux-image-5.4.0-1029-raspi, see
https://packages.ubuntu.com/focal-updates/linux-image-raspi
I think you should run
```docker build --build-arg UNAME_R=5.4.0-1029-raspi -t rtwg-image .```

**Comment by LanderU** [comment]
@razr, thanks a lot for your response. Yes this is what I did, but now the patch step is not working, see the error:

```bash
patching file virt/kvm/arm/arch_timer.c
patching file virt/kvm/arm/arm.c
The command '/bin/sh -c cd $HOME/linux_build && cd `ls -d */`     && patch -p1 < ../patch-${RT_PATCH}.patch' returned a non-zero code: 1
```

This is very sensitive, IMHO we should

1. Update the default argument to point to `5.4.0-1029-raspi` instead of `5.4.0-1022-raspi`
2. Find the correct patch version for this kernel
3. Add a note in the README.md about how to build with different arguments

I'll open a PR to fix the 1 and 3.

**Comment by LanderU** [comment]
@razr, just as update, I've fixed the issue by changing the values to:

```bash
UNAME_R=5.4.0-1029-raspi
RT_PATCH=5.4.87-rt48
```

**Comment by razr** [comment]
great, could you please submit a pull request?

**Comment by razr** [comment]
@christophebedard I have seen that Ubuntu 20.04 has changed the kernel version and https://docs.ros.org/en/foxy/Tutorials/Building-Realtime-rt_preempt-kernel-for-ROS-2.html is obsolete. Should we update it? Another possibility would be to say on the documentation page: this is an example of how to configure RT kernel, please look at the ROS2 real-time group repo for the detailed instructions.

**Comment by LanderU** [comment]
@razr, yes, will do so, also I'll update in the same PR the README to adjust the content to the new changes.
