### ISSUE TITLE
Make fail - make: *** No rule to make target 'deb-pkg'.  Stop.

### ISSUE THREAD

**Issue by sbhrepo** [ros-realtime/rt-kernel-docker-builder#10]
I followed the guide and this is what I saw:
docker build fail if you specify the kernel version and the RT_PATCH version. if you run the build command without this two parameters it build the image.
then I run the docker image and tried to run the make command and I got the following error:

user@user-VirtualBox:~/Documents/rt-kernel-docker-builder$ docker run -t -i rtwg-image bash
user@5a3e5f043b21:~/linux_build$ ls -la
total 178432
drwxr-xr-x 1 user user      4096 Aug  4 16:04 .
drwxr-xr-x 1 user user      4096 Aug  4 16:04 ..
-rw-rw-r-- 1 root root        85 Aug  4 15:40 .config-fragment
drwxr-xr-x 1 user user      4096 Aug  4 16:05 linux-raspi-5.4.0
-rw-r--r-- 1 user user  11583830 Jul 20 17:01 linux-raspi_5.4.0-1041.45.diff.gz
-rw-r--r-- 1 user user      3546 Jul 20 17:01 linux-raspi_5.4.0-1041.45.dsc
-rw-r--r-- 1 user user 170244619 Apr  3  2020 linux-raspi_5.4.0.orig.tar.gz
-rw-r--r-- 1 user user    859109 Jul  9 18:57 patch-5.4.129-rt61.patch
user@5a3e5f043b21:~/linux_build$ make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- -j `nproc` deb-pkg
make: *** No rule to make target 'deb-pkg'.  Stop.

any suggestion how to solve it?

**Comment by razr** [comment]
you need to:
```bash
cd linux-raspi-5.4.0
```
I think this step is missing in the description
