### ISSUE TITLE
Which Ubuntu 20.04 image to install on RaspberryPi?

### ISSUE THREAD

**Issue by JanStaschulat** [ros-realtime/rt-kernel-docker-builder#26]
Which Ubuntu 20.04 image for RaspberryPi 4B should I install as pre-requisite for the rt_preempt kernel patch?

With `Raspberry Pi Imager v.1.6.2` I could choose `Ubuntu Server 20.04.3 LTS(RPi 2/3/4/400) 64-bit server OS with long-term support for arm64 architectures, (2021-08-26)` but not the `Ubuntu 20.04 Desktop` version. 

The following link in the documentation on https://github.com/ros-realtime/rt-kernel-docker-builder **Download and install Ubuntu 20.04 image**

https://ubuntu.com/download/raspberry-pi/thank-you?version=20.04&architecture=arm64+raspi
does not work ("File not found"):
https://cdimage.ubuntu.com/releases/20.04/release/ubuntu-20.04-preinstalled-arm64+raspi.img.xz

**Comment by razr** [comment]
Indeed, it looks like there is no Ubuntu 20.04 Desktop RPI4 image anymore. Could you please try the [Ubuntu server](https://cdimage.ubuntu.com/releases/20.04/release/ubuntu-20.04.3-preinstalled-server-arm64+raspi.img.xz) and let us know how it works?
