### ISSUE TITLE
Move shuhaowu/ros-realtime-rpi4-image to ros-realtime

### ISSUE THREAD

**Issue by shuhaowu** [ros-realtime/rt-kernel-docker-builder#30]
As discussed in the RTWG meeting, the RTWG is happy to host the Raspberry Pi 4 + RT + ROS image builder (https://github.com/shuhaowu/ros-realtime-rpi4-image) that I worked on. I'm also happy to contribute it upstream under an open source license. I'm not sure what the process should be, as this probably hasn't been done before, but I have a few items:

- [x] **Figure out how to transfer the repo**: I can transfer the repo to one of the organization members (**who?**), who can then transfer it to the ros-realtime organization.
- [x] **Licensing**: Apache license.
- [x] **Future maintenance**: As I mentioned in the RTWG meeting, I am happy to continue maintain the code via code reviews and changes. While I don't use it _actively_ on a live robot, I'm using the same image builder for similar projects. My preference for the time being, if the RTWG is OK with it, is to retain at least some sort of committer access to this.
- [x] **CI/CD/Release**: In my repo, I have it working with Github CI. The build takes 15 minutes without compression using the Github builder. The image without compression is about 8GB and with compression is about 1.7GB (with galactic installed, iirc). Compression takes longer than the build using Github's builder, but only about 5 minutes on my workstation (Ryzen 7 3700X). We'll need to figure out host this. Github release might be ok if we compress, as [it says we can host 2GB files with no bandwidth limits](https://docs.github.com/en/repositories/releasing-projects-on-github/about-releases#storage-and-bandwidth-quotas).

Other items like what images we should build, what tools should we include preferably should be answered in a separate issue, perhaps in the final repo once it is created. I expected that we need to make a few changes to the builder, as I've only tested it with a single build configuration for now. I also expect that we need to change the docs a bit as the docs right now only target people who develop this project instead of the users.

cc: @LanderU @carlossvg

**Comment by LanderU** [comment]
Hey @shuhaowu, sorry for the late response. Yes, you can transfer the repo to my user and I'll add the repo to our org and add you as a maintainer. Does it make sense to you?

After that, we can check if we can improve the compress time and push publish the image somewhere. Thanks a lot!

**Comment by shuhaowu** [comment]
Sounds good to me. I'll transfer the repo to you in a few minutes. We can work out the technical details after the transfer is complete. Thanks!

**Comment by LanderU** [comment]
@shuhaowu, done: https://github.com/ros-realtime/ros-realtime-rpi4-image, I added you as an admin also @christophebedard @carlossvg and @razr are admins

**Comment by shuhaowu** [comment]
Thanks so much! I suppose I can close this issue now. Later today I'll create a few issue about the technical stuff in that repo.
